In [4]:
%pip install pandas numpy openpyxl

Collecting pandas
  Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\gogar\anaconda3\envs\troncal\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\Users\gogar\anaconda3\envs\troncal\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ----------------------------------- ---- 8.7/9.7 MB 46.6 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 41.8 MB/s  0:00:00
Downloading numpy-2.4.3-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------  12.1/12.3 MB 63.8 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 51.9 MB/s  0:00:00
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, et-xmlfile, pandas, openpyxl

   ---------------------------------------- 0/5 [tzdata]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   ---------------------------------------- 5/5 [openpyxl]

Successfully installed et-xmlfile-2.0.0 numpy-2.4.3 openpyxl-3.1.5 pandas-3.0.1 tzdata-2025.3
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd 
import numpy as np

In [17]:
df_base=pd.read_csv('../Datasets/Dataset_para_Modelos.csv', thousands=',', decimal='.')
df_base

,fecha_albaran,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,...,margen_beneficio,por_margen_calc,margen_calc,tipo_abc,agrupacion_listado,agrupacion_canal,anio,mes,semana_anio,trimestre
0,2022-03-31,18582,FB4068772000,800.0,0.385,0.2767,221.3969,308.00,308.00,308.00,...,86.603092,28.12,86.6031,C,12,Partners,2022,3,13,1
1,2024-08-28,18582,FB4068772000,600.0,0.390,0.2876,172.5574,234.00,234.00,234.00,...,61.442609,26.26,61.4426,C,12,Partners,2024,8,35,3
2,2024-04-26,18582,FB4068772000,600.0,0.390,0.2863,171.7935,234.00,234.00,234.00,...,62.206486,26.58,62.2065,C,12,Partners,2024,4,17,2
3,2023-07-20,18555,012-129,2.0,0.580,0.0976,0.1953,1.16,1.16,1.16,...,0.964734,83.16,0.9647,C,012R,Distribución,2023,7,29,3
4,2023-07-20,18555,012-130,2.0,0.580,0.0975,0.1950,1.16,1.16,1.16,...,0.964987,83.19,0.9650,C,012R,Distribución,2023,7,29,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857057,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,119.888998,36.03,119.8890,B,941,Distribución,2023,9,37,3
857058,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,119.888998,36.03,119.8890,B,941,Distribución,2023,9,37,3
857059,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,119.888998,36.03,119.8890,B,941,Distribución,2023,9,37,3
857060,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,119.888998,36.03,119.8890,B,941,Distribución,2023,9,37,3
857061,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,119.888998,36.03,119.8890,B,941,Distribución,2023,9,37,3

In [18]:
df_clientes=pd.read_excel('../Datasets/Maestro_Clientes.xlsx')
df_clientes

,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz
0,60727,ESPAÑA,ABRERA,BARCELONA,UE,UsuarioCR
1,61028,ESPAÑA,ABRERA,BARCELONA,UE,UsuarioCR
2,60541,ESPAÑA,AIGUAFREDA,BARCELONA,UE,UsuarioCR
3,60321,ESPAÑA,BADALONA,BARCELONA,UE,UsuarioCR
4,60914,ESPAÑA,BADALONA,BARCELONA,UE,UsuarioCR
...,...,...,...,...,...,...
3981,18595,FRANCIA,LA RICAMARIE,NaN,UE,CruzExLCV
3982,18060,FRANCIA,VILLEURBANNE,NaN,UE,CruzExNEW1
3983,18740,FRANCIA,MANDALIEU LA NAPOULE,NaN,UE,CruzExB
3984,18598,FRANCIA,MALNOUE EMERAINVILLE,NaN,UE,CruzExFLEET
3985,18213,FRANCIA,WAALWIJK,NaN,UE,CruzExLCV

In [ ]:
#Hacemos merge uniendo ambas tablas por el CodigoCliente

df_union=pd.merge(left=df_base, right=df_clientes, left_on='codigo_cliente', right_on='CodigoCliente', how='left')
df_union

,fecha_albaran,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,...,anio,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz
0,2022-03-31,18582,FB4068772000,800.0,0.385,0.2767,221.3969,308.00,308.00,308.00,...,2022,3,13,1,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
1,2024-08-28,18582,FB4068772000,600.0,0.390,0.2876,172.5574,234.00,234.00,234.00,...,2024,8,35,3,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
2,2024-04-26,18582,FB4068772000,600.0,0.390,0.2863,171.7935,234.00,234.00,234.00,...,2024,4,17,2,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
3,2023-07-20,18555,012-129,2.0,0.580,0.0976,0.1953,1.16,1.16,1.16,...,2023,7,29,3,18555,REPUBLICA CHECA,PRAHA 5-RADOTIN,NaN,UE,CruzExA
4,2023-07-20,18555,012-130,2.0,0.580,0.0975,0.1950,1.16,1.16,1.16,...,2023,7,29,3,18555,REPUBLICA CHECA,PRAHA 5-RADOTIN,NaN,UE,CruzExA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857057,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
857058,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
857059,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
857060,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
857061,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA

In [25]:
#Creamos el dataframe maestro solo para españa y para resto de paises
condicion=df_union['Pais']== 'ESPAÑA'
condicion2=df_union['Pais']!= 'ESPAÑA'
df_espana=df_union[condicion]
df_resto=df_union[condicion2]

display(df_espana)
display(df_resto)

,fecha_albaran,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,...,anio,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz
5,2021-08-13,10669,813-002,20.0,1.000,0.2732,5.4635,20.00,20.00,22.9900,...,2021,8,32,3,10669,ESPAÑA,MALAGA,MALAGA,UE,Cruz3
6,2022-07-13,17128,890-122,2.0,1.000,0.1012,0.2024,2.00,2.00,2.4200,...,2022,7,28,3,17128,ESPAÑA,BURGOS,BURGOS,UE,CruzND
10,2020-09-24,50017,813-351,2.0,1.280,0.3002,0.6004,2.56,2.56,3.0976,...,2020,9,39,3,50017,ESPAÑA,BARCELONA,BARCELONA,UE,UsuarioRK
11,2020-07-14,50010,813-351,4.0,1.280,0.2903,1.1613,5.12,5.12,6.1952,...,2020,7,29,3,50010,ESPAÑA,BARCELONA,BARCELONA,UE,UsuarioRK
18,2024-01-15,60000,012-086,1.0,1.612,0.0366,0.0366,1.61,1.61,1.9481,...,2024,1,3,1,60000,ESPAÑA,NaN,NaN,UE,UsuarioCR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850707,2022-03-01,11117,925-773,1.0,123.926,29.4304,29.4304,123.93,57.01,68.9821,...,2022,3,9,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1
850708,2020-02-06,11117,924-602,1.0,123.967,32.6790,32.6790,123.97,57.03,69.0063,...,2020,2,6,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1
850709,2021-09-21,11117,923-307,1.0,126.405,29.8093,29.8093,126.41,58.15,70.3615,...,2021,9,38,3,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1
850710,2021-06-11,11117,923-306,1.0,126.405,30.0177,30.0177,126.41,58.15,70.3615,...,2021,6,23,2,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1
850882,2021-04-23,11117,909-153,1.0,227.273,65.0035,65.0035,227.27,104.54,126.4934,...,2021,4,16,2,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1

,fecha_albaran,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,...,anio,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz
0,2022-03-31,18582,FB4068772000,800.0,0.385,0.2767,221.3969,308.00,308.00,308.00,...,2022,3,13,1,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
1,2024-08-28,18582,FB4068772000,600.0,0.390,0.2876,172.5574,234.00,234.00,234.00,...,2024,8,35,3,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
2,2024-04-26,18582,FB4068772000,600.0,0.390,0.2863,171.7935,234.00,234.00,234.00,...,2024,4,17,2,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
3,2023-07-20,18555,012-129,2.0,0.580,0.0976,0.1953,1.16,1.16,1.16,...,2023,7,29,3,18555,REPUBLICA CHECA,PRAHA 5-RADOTIN,NaN,UE,CruzExA
4,2023-07-20,18555,012-130,2.0,0.580,0.0975,0.1950,1.16,1.16,1.16,...,2023,7,29,3,18555,REPUBLICA CHECA,PRAHA 5-RADOTIN,NaN,UE,CruzExA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857057,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
857058,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
857059,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
857060,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
857061,2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA

In [ ]:
df_espana.set_index('fecha_albaran', inplace=True)
df_espana

KeyError: "None of ['fecha_albaran'] are in the columns"

In [32]:
df_espana['anio_semana'] = df_espana['anio'].astype(str) + '-' + df_espana['semana_anio'].astype(str)
df_espana

,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,base_imponible,...,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz,anio_semana
fecha_albaran,,,,,,,,,,,,,,,,,,,,,
2021-08-13,10669,813-002,20.0,1.000,0.2732,5.4635,20.00,20.00,22.9900,19.00,...,8,32,3,10669,ESPAÑA,MALAGA,MALAGA,UE,Cruz3,2021-32
2022-07-13,17128,890-122,2.0,1.000,0.1012,0.2024,2.00,2.00,2.4200,2.00,...,7,28,3,17128,ESPAÑA,BURGOS,BURGOS,UE,CruzND,2022-28
2020-09-24,50017,813-351,2.0,1.280,0.3002,0.6004,2.56,2.56,3.0976,2.56,...,9,39,3,50017,ESPAÑA,BARCELONA,BARCELONA,UE,UsuarioRK,2020-39
2020-07-14,50010,813-351,4.0,1.280,0.2903,1.1613,5.12,5.12,6.1952,5.12,...,7,29,3,50010,ESPAÑA,BARCELONA,BARCELONA,UE,UsuarioRK,2020-29
2024-01-15,60000,012-086,1.0,1.612,0.0366,0.0366,1.61,1.61,1.9481,1.61,...,1,3,1,60000,ESPAÑA,NaN,NaN,UE,UsuarioCR,2024-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-01,11117,925-773,1.0,123.926,29.4304,29.4304,123.93,57.01,68.9821,57.01,...,3,9,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2022-9
2020-02-06,11117,924-602,1.0,123.967,32.6790,32.6790,123.97,57.03,69.0063,57.03,...,2,6,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2020-6
2021-09-21,11117,923-307,1.0,126.405,29.8093,29.8093,126.41,58.15,70.3615,58.15,...,9,38,3,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-38
2021-06-11,11117,923-306,1.0,126.405,30.0177,30.0177,126.41,58.15,70.3615,58.15,...,6,23,2,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-23
2021-04-23,11117,909-153,1.0,227.273,65.0035,65.0035,227.27,104.54,126.4934,104.54,...,4,16,2,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-16

In [29]:
df_resto.set_index('fecha_albaran', inplace=True)
df_resto

,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,base_imponible,...,anio,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz
fecha_albaran,,,,,,,,,,,,,,,,,,,,,
2022-03-31,18582,FB4068772000,800.0,0.385,0.2767,221.3969,308.00,308.00,308.00,308.00,...,2022,3,13,1,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
2024-08-28,18582,FB4068772000,600.0,0.390,0.2876,172.5574,234.00,234.00,234.00,234.00,...,2024,8,35,3,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
2024-04-26,18582,FB4068772000,600.0,0.390,0.2863,171.7935,234.00,234.00,234.00,234.00,...,2024,4,17,2,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN
2023-07-20,18555,012-129,2.0,0.580,0.0976,0.1953,1.16,1.16,1.16,1.16,...,2023,7,29,3,18555,REPUBLICA CHECA,PRAHA 5-RADOTIN,NaN,UE,CruzExA
2023-07-20,18555,012-130,2.0,0.580,0.0975,0.1950,1.16,1.16,1.16,1.16,...,2023,7,29,3,18555,REPUBLICA CHECA,PRAHA 5-RADOTIN,NaN,UE,CruzExA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,2023,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA

In [33]:
df_resto['anio_semana'] = df_resto['anio'].astype(str) + '-' + df_resto['semana_anio'].astype(str)
df_resto

,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,base_imponible,...,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz,anio_semana
fecha_albaran,,,,,,,,,,,,,,,,,,,,,
2022-03-31,18582,FB4068772000,800.0,0.385,0.2767,221.3969,308.00,308.00,308.00,308.00,...,3,13,1,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN,2022-13
2024-08-28,18582,FB4068772000,600.0,0.390,0.2876,172.5574,234.00,234.00,234.00,234.00,...,8,35,3,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN,2024-35
2024-04-26,18582,FB4068772000,600.0,0.390,0.2863,171.7935,234.00,234.00,234.00,234.00,...,4,17,2,18582,ITALIA,PIANDIMELETO,NaN,UE,CruzExPARTN,2024-17
2023-07-20,18555,012-129,2.0,0.580,0.0976,0.1953,1.16,1.16,1.16,1.16,...,7,29,3,18555,REPUBLICA CHECA,PRAHA 5-RADOTIN,NaN,UE,CruzExA,2023-29
2023-07-20,18555,012-130,2.0,0.580,0.0975,0.1950,1.16,1.16,1.16,1.16,...,7,29,3,18555,REPUBLICA CHECA,PRAHA 5-RADOTIN,NaN,UE,CruzExA,2023-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA,2023-37
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA,2023-37
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA,2023-37
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA,2023-37
2023-09-11,18788,941-036,4.0,319.950,53.2153,212.8610,1279.80,332.75,332.75,332.75,...,9,37,3,18788,CANADA,VANCOUVER,NaN,AMERICA,CruzExA,2023-37

In [ ]:
cond_año=df_espana['']

,codigo_cliente,codigo_articulo,unidades,precio,precio_coste,importe_coste,importe_bruto,importe_neto,importe_liquido,base_imponible,...,mes,semana_anio,trimestre,CodigoCliente,Pais,Municipio,Provincia,Zona,TipoCruz,anio_semana
fecha_albaran,,,,,,,,,,,,,,,,,,,,,
2021-08-13,10669,813-002,20.0,1.000,0.2732,5.4635,20.00,20.00,22.9900,19.00,...,8,32,3,10669,ESPAÑA,MALAGA,MALAGA,UE,Cruz3,2021-32
2022-07-13,17128,890-122,2.0,1.000,0.1012,0.2024,2.00,2.00,2.4200,2.00,...,7,28,3,17128,ESPAÑA,BURGOS,BURGOS,UE,CruzND,2022-28
2020-09-24,50017,813-351,2.0,1.280,0.3002,0.6004,2.56,2.56,3.0976,2.56,...,9,39,3,50017,ESPAÑA,BARCELONA,BARCELONA,UE,UsuarioRK,2020-39
2020-07-14,50010,813-351,4.0,1.280,0.2903,1.1613,5.12,5.12,6.1952,5.12,...,7,29,3,50010,ESPAÑA,BARCELONA,BARCELONA,UE,UsuarioRK,2020-29
2024-01-15,60000,012-086,1.0,1.612,0.0366,0.0366,1.61,1.61,1.9481,1.61,...,1,3,1,60000,ESPAÑA,NaN,NaN,UE,UsuarioCR,2024-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-03-01,11117,925-773,1.0,123.926,29.4304,29.4304,123.93,57.01,68.9821,57.01,...,3,9,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2022-9
2020-02-06,11117,924-602,1.0,123.967,32.6790,32.6790,123.97,57.03,69.0063,57.03,...,2,6,1,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2020-6
2021-09-21,11117,923-307,1.0,126.405,29.8093,29.8093,126.41,58.15,70.3615,58.15,...,9,38,3,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-38
2021-06-11,11117,923-306,1.0,126.405,30.0177,30.0177,126.41,58.15,70.3615,58.15,...,6,23,2,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-23
2021-04-23,11117,909-153,1.0,227.273,65.0035,65.0035,227.27,104.54,126.4934,104.54,...,4,16,2,11117,ESPAÑA,VALDEMORO,MADRID,UE,Cruz1,2021-16

In [36]:
#guardamos los df
df_espana.to_csv('Dataset_España.csv', index=True, sep=';')
df_resto.to_csv('Dataset_Resto.csv', index=True, sep=';')